Algoritmo "L02I"
// Disciplina   : (Lógica de Programação com Javascript)
// Professor    : Jailson Costa dos Santos
// Descrição    : Elaborar um programa que efetue a leitura de um número inteiro e apresentar uma mensagem
//informando se o número é par ou ímpar.
// Autor(a)     : Laryssa Daniela
// Data atual   : 25/09/2026
Var
   // Seção de Declarações das variáveis
   N: inteiro
Inicio
   // Mensagens iniciais informativas
   Escreval("Digite um numero inteiro: ")
   Leia(N)
   se (N mod 2 = 0) entao
      Escreval("O numero e PAR.")
   senao
      Escreval("O numero e IMPAR.")
   fimse

Fimalgoritmo