Algoritmo "L02K"
// Disciplina   : (Lógica de Programação com Javascript)
// Professor    : Jailson Costa dos Santos
// Descrição    : Elaborar um programa que efetue a leitura de um determinado valor inteiro, e efetue a sua
//apresentação, caso o valor não seja maior que três.
// Autor(a)     : Laryssa Daniela
// Data atual   : 25/09/2026
Var
   // Seção de Declarações das variáveis
   N: inteiro
Inicio
   // Mensagens iniciais informativas
   Escreval("Digite um numero inteiro: ")
   Leia(N)
   se nao (N > 3) entao
      Escreval("O valor fornecido e: ", N)
   fimse
Fimalgoritmo